from datetime import datetime
from datetime import timezone

from src.entity import SpainFuelPrice


def get_mapped_spain_fuel_price_data():
    expected_datetime_obj = datetime(2024, 3, 12, 18, 48, 4, tzinfo=timezone.utc)
    return [
        SpainFuelPrice(
            timestamp=expected_datetime_obj,
            date=expected_datetime_obj.date(),
            hour=expected_datetime_obj.hour,
            zip_code=48170,
            municipality_id=7563,
            province_id=48,
            sale_type="p",
            label="petroprix",
            address="poligono ugaldeguren, 25",
            municipality="zamudio",
            province="bizkaia",
            locality="zamudio",
            latitude=43.286000,
            longitude=-2.872639,
            biodiesel_price=None,
            bioethanol_price=None,
            compressed_natural_gas_price=None,
            liquefied_natural_gas_price=None,
            liquefied_petroleum_gases_price=None,
            diesel_a_price=1.389,
            diesel_b_price=None,
            diesel_premium_price=None,
            gasoline_95_e10_price=None,
            gasoline_95_e5_price=1.539,
            gasoline_95_e5_premium_price=None,
            gasoline_98_e10_price=None,
            gasoline_98_e5_price=None,
            hydrogen_price=None,
        ),
        SpainFuelPrice(
            timestamp=expected_datetime_obj,
            date=expected_datetime_obj.date(),
            hour=expected_datetime_obj.hour,
            zip_code=15570,
            municipality_id=2172,
            province_id=15,
            sale_type="p",
            label="sbc",
            address="avenida do mar, 94",
            municipality="narón",
            province="coruña (a)",
            locality="gandara",
            latitude=43.488583,
            longitude=-8.200111,
            biodiesel_price=None,
            bioethanol_price=None,
            compressed_natural_gas_price=None,
            liquefied_natural_gas_price=None,
            liquefied_petroleum_gases_price=None,
            diesel_a_price=1.399,
            diesel_b_price=None,
            diesel_premium_price=None,
            gasoline_95_e10_price=None,
            gasoline_95_e5_price=1.499,
            gasoline_95_e5_premium_price=None,
            gasoline_98_e10_price=None,
            gasoline_98_e5_price=None,
            hydrogen_price=None,
        ),
    ]
