def get_response_raw_data():
    return {
        "Fecha": "09/10/2024 20:12:15",
        "ListaEESSPrecio": [
            {
                "C.P.": "02250",
                "Dirección": "AVENIDA CASTILLA LA MANCHA, 26",
                "Horario": "L-D: 07:00-22:00",
                "Latitud": "39,211417",
                "Localidad": "ABENGIBRE",
                "Longitud (WGS84)": "-1,539167",
                "Municipio": "Abengibre",
                "Precio Biodiesel": "",
                "Precio Bioetanol": "",
                "Precio Gas Natural Comprimido": "",
                "Precio Gas Natural Licuado": "",
                "Precio Gases licuados del petróleo": "",
                "Precio Gasoleo A": "1,299",
                "Precio Gasoleo B": "0,899",
                "Precio Gasoleo Premium": "",
                "Precio Gasolina 95 E10": "",
                "Precio Gasolina 95 E5": "1,399",
                "Precio Gasolina 95 E5 Premium": "",
                "Precio Gasolina 98 E10": "",
                "Precio Gasolina 98 E5": "",
                "Precio Hidrogeno": "",
                "Provincia": "ALBACETE",
                "Rótulo": "Nº 10.935",
                "Tipo Venta": "P",
                "IDEESS": "4375",
                "IDMunicipio": "52",
                "IDProvincia": "02",
                "IDCCAA": "07",
            },
            {
                "C.P.": "02152",
                "Dirección": "CR CM-332, 46,4",
                "Horario": "L-D: 7:00-23:00",
                "Latitud": "39,100389",
                "Localidad": "ALATOZ",
                "Longitud (WGS84)": "-1,346083",
                "Municipio": "Alatoz",
                "Precio Biodiesel": "",
                "Precio Bioetanol": "",
                "Precio Gas Natural Comprimido": "",
                "Precio Gas Natural Licuado": "",
                "Precio Gases licuados del petróleo": "",
                "Precio Gasoleo A": "1,589",
                "Precio Gasoleo B": "",
                "Precio Gasoleo Premium": "1,709",
                "Precio Gasolina 95 E10": "",
                "Precio Gasolina 95 E5": "1,699",
                "Precio Gasolina 95 E5 Premium": "",
                "Precio Gasolina 98 E10": "",
                "Precio Gasolina 98 E5": "",
                "Precio Hidrogeno": "",
                "Provincia": "ALBACETE",
                "Rótulo": "REPSOL",
                "Tipo Venta": "P",
                "IDEESS": "5122",
                "IDMunicipio": "53",
                "IDProvincia": "02",
                "IDCCAA": "07",
            },
        ],
        "Nota": "Archivo de todos los productos en todas las estaciones de servicio. La actualización de precios "
                "se realiza cada media hora, con los precios en vigor en ese momento.",
        "ResultadoConsulta": "OK"
    }
