name: "Destroy Infrastructure Manually"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_PREFIX: travass
      TF_VAR_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_REGION: europe-west1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.6
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Terraform
        id: setup-tf
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        id: init
        working-directory: tf_infra/
        run: terraform init

      - name: Destroy Terraform Resources
        id: apply
        working-directory: tf_infra/
        run: terraform destroy -auto-approve
