name: Trigger Ingestor

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run-ingestor:
    uses: ./.github/workflows/run-python-job-reusable.yaml
    with:
      working_directory: fuel-ingestor
      script_path: app/ingestor/main.py
    secrets:
      gcp_credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

  run-aggregation:
    needs: run-ingestor
    uses: ./.github/workflows/run-python-job-reusable.yaml
    with:
      working_directory: fuel-ingestor
      script_path: app/aggregator/main.py
    secrets:
      gcp_credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
