name: Trigger Ingestor

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  trigger-ingestor:
    uses: gerardovitale/github-workflows/.github/workflows/trigger-cloud-run-job.yml@v1
    with:
      region: europe-southwest1
      app_name: travass
      component: fuel-ingestor-job
    secrets:
      gcp_credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
